# Generated by Django 5.0.4 on 2024-05-12 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('line_id', models.CharField(max_length=255, unique=True, verbose_name='LINE ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('duration', models.FloatField(verbose_name='所要時間')),
                ('price', models.IntegerField(verbose_name='料金')),
                ('description', models.TextField(verbose_name='詳細')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reservation/service', verbose_name='画像')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'サービス',
                'verbose_name_plural': 'サービス',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reservation/store', verbose_name='画像')),
                ('open_time', models.TimeField(default='09:00:00', verbose_name='開店時間')),
                ('close_time', models.TimeField(default='21:00:00', verbose_name='閉店時間')),
                ('closed_monday', models.BooleanField(default=False, verbose_name='月曜定休')),
                ('closed_tuesday', models.BooleanField(default=False, verbose_name='火曜定休')),
                ('closed_wednesday', models.BooleanField(default=False, verbose_name='水曜定休')),
                ('closed_thursday', models.BooleanField(default=False, verbose_name='木曜定休')),
                ('closed_friday', models.BooleanField(default=False, verbose_name='金曜定休')),
                ('closed_saturday', models.BooleanField(default=False, verbose_name='土曜定休')),
                ('closed_sunday', models.BooleanField(default=False, verbose_name='日曜定休')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='未設定', max_length=100, verbose_name='職位')),
                ('nomination_fee', models.IntegerField(default=0, verbose_name='指名料')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reservation/staff', verbose_name='画像')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('services', models.ManyToManyField(related_name='staff', to='app.service', verbose_name='サービス')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='予約日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='お客様情報')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service', verbose_name='サービス')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
            },
        ),
        migrations.CreateModel(
            name='StaffHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(verbose_name='休日')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'スタッフ休日',
                'verbose_name_plural': 'スタッフ休日',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.store', verbose_name='店舗'),
        ),
        migrations.CreateModel(
            name='StoreHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(verbose_name='休業日')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '店舗休業日',
                'verbose_name_plural': '店舗休業日',
            },
        ),
    ]
